name: Diff builds on Pull Requests

on:
  pull_request:
    branches:
    - main

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - name: (main) Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
    - name: (main) Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: (main) Install npm
      run: npm ci
    - name: (main) Run eleventy
      run: npm run build
    - name: (main) Move build
      run: mv build ${{ runner.temp }}/build_main
    - name: (HEAD) Checkout repository
      uses: actions/checkout@v3
    - name: (HEAD) Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: (HEAD) Install npm
      run: npm ci
    - name: (HEAD) Run eleventy
      run: npm run build
    - name: (HEAD) Compare builds
      run: diff -r ${{ runner.temp }}/build_main build
